kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-laravel-nginx-config
data:
  nginx.conf: |
    {{ .Values.configMaps.nginxConf |  nindent 6}} 

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-env
data:
  env: |
    {{ .Values.configMaps.env |  nindent 6}} 
    