{{- $root := . -}}
{{- range $i, $item := .Values.app }}
{{- with $root }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ $item.version }}
  labels:
    version: {{ $item.version }}
    {{- include "istio-laravel-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      version: {{ $item.version }}
      {{- include "istio-laravel-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        version: {{ $item.version }}
        {{- include "istio-laravel-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: 
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-php-fpm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $item.image }}:{{ $item.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if $item.env }}
          env:
            {{- toYaml $item.env | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-www
            - mountPath: /data
              name: {{ .Release.Name }}-env
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html && cp /data/env /var/www/html/.env && chmod -R 777 /var/www/html/storage && chmod -R 777 /var/www/html/bootstrap/cache"]
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"

        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-www
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: {{ .Release.Name }}-laravel-nginx-config
          resources:
            limits:
              cpu: "0.1"
              memory: "200Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          {{- if .Values.healthCheck.enable }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

      volumes:
        - name: nginx-www
          emptyDir: {}
        - name: {{ .Release.Name }}-env
          configMap: 
            name: {{ .Release.Name }}-env
            items:
              - key: env
                path: env
        - name: {{ .Release.Name }}-laravel-nginx-config
          configMap:
            name: {{ .Release.Name }}-laravel-nginx-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
